version: 2
updates:
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the following directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
      
  -  package-ecosystem: "gomod"
    # Look for a `Dockerfile` in the following directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"