---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  Creates ECR and user to push containers for deployment

Resources:
  MyUser:
    Type: AWS::IAM::User
    Properties: 
      UserName: MyECRUser

  MyAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      Status: Active
      UserName: !Ref MyUser
    DependsOn: MyUser

  MyECRPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: AllowECRPushPull
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
              - "ecr:GetAuthorizationToken"
            Resource: '*'
      Users:
        - !Ref MyUser
    DependsOn: MyUser


  MyRepository:
    Type: AWS::ECR::Repository
    Properties: 
      ImageScanningConfiguration: 
          ScanOnPush: False
      ImageTagMutability: MUTABLE
      RepositoryName: docker-golang-demo
    DependsOn: MyAccessKey

Outputs:
  RepoURL:
    Value: !GetAtt MyRepository.RepositoryUri
  AccessKey:
    Value: !Ref MyAccessKey
  AccessSecret:
    Value: !GetAtt MyAccessKey.SecretAccessKey















